name: Auto-update Gist Status

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  update-gist-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests PyGithub

      - name: Update Gist Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python .github/scripts/update_gist_status.py
